const data = [
  {
    label: "EDP",
    name: "EDP S.A.",
    mktCap: 18210000000,
    mktCapPerf1Y: 26.18,
    sector: "Utilities",
  },
  {
    label: "BCP",
    name: "Banco Comercial Portugues S.A.",
    mktCap: 15320000000,
    mktCapPerf1Y: 41.36,
    sector: "Finance",
  },
  {
    label: "EDPR",
    name: "EDP Renewables SA",
    mktCap: 14490000000,
    mktCapPerf1Y: 67.07,
    sector: "Utilities",
  },
  {
    label: "GALP",
    name: "Galp Energia, SGPS S.A. Class B",
    mktCap: 13650000000,
    mktCapPerf1Y: 37.93,
    sector: "Energy minerals",
  },
  {
    label: "JMT",
    name: "Jeronimo Martins, SGPS S.A.",
    mktCap: 10960000000,
    mktCapPerf1Y: -17.26,
    sector: "Retail trade",
  },
  {
    label: "SON",
    name: "Sonae SGPS SA",
    mktCap: 3930000000,
    mktCapPerf1Y: 51.44,
    sector: "Technology services",
  },
  {
    label: "NOS",
    name: "NOS SGPS SA",
    mktCap: 2690000000,
    mktCapPerf1Y: 36.55,
    sector: "Communications",
  },
  {
    label: "NVG",
    name: "Navigator Company SA",
    mktCap: 2470000000,
    mktCapPerf1Y: -3.58,
    sector: "Process industries",
  },
  {
    label: "RENE",
    name: "Redes Energeticas Nacionais SA",
    mktCap: 2390000000,
    mktCapPerf1Y: 23.58,
    sector: "Utilities",
  },
  {
    label: "SEM",
    name: "Semapa Sociedade de Investimento e Gestao SGPS SA",
    mktCap: 1800000000,
    mktCapPerf1Y: 32.47,
    sector: "Process industries",
  },
  {
    label: "EGL",
    name: "Mota-Engil SGPS SA",
    mktCap: 1400000000,
    mktCapPerf1Y: 7.02,
    sector: "Industrial services",
  },
  {
    label: "ALTR",
    name: "Altri, SGPS, S.A.",
    mktCap: 1020000000,
    mktCapPerf1Y: -8.02,
    sector: "Process industries",
  },
  {
    label: "SNC",
    name: "Sonaecom SGPS SA",
    mktCap: 886730000,
    mktCapPerf1Y: 22.13,
    sector: "Technology services",
  },
  {
    label: "COR",
    name: "Corticeira Amorim SGPS SA",
    mktCap: 867160000,
    mktCapPerf1Y: -14.95,
    sector: "Process industries",
  },
  {
    label: "CTT",
    name: "CTT - Correios de Portugal SA",
    mktCap: 804930000,
    mktCapPerf1Y: -16.1,
    sector: "Transportation",
  },
  {
    label: "IBS",
    name: "Ibersol, SGPS S.A.",
    mktCap: 405270000,
    mktCapPerf1Y: 20.99,
    sector: "Consumer services",
  },
  {
    label: "NBA",
    name: "Novabase SGPS SA",
    mktCap: 309640000,
    mktCapPerf1Y: 0.17,
    sector: "Technology services",
  },
  {
    label: "SCT",
    name: "TOYOTA CAETANO PORTUGAL",
    mktCap: 262500000,
    mktCapPerf1Y: 25.86,
    sector: "Retail trade",
  },
  {
    label: "MAR",
    name: "Martifer SGPS",
    mktCap: 242000000,
    mktCapPerf1Y: 12.2,
    sector: "Industrial services",
  },
  {
    label: "TDSA",
    name: "Teixeira Duarte, S.A.",
    mktCap: 208740000,
    mktCapPerf1Y: 42.54,
    sector: "Industrial services",
  },
  {
    label: "SCP",
    name: "Sporting Clube de Portugal Futebol SAD",
    mktCap: 201990000,
    mktCapPerf1Y: 0.0,
    sector: "Consumer services",
  },
  {
    label: "VAF",
    name: "VAA Vista Alegre Atlantis SGPS SA",
    mktCap: 179390000,
    mktCapPerf1Y: 9.0,
    sector: "Consumer durables",
  },
  {
    label: "RAM",
    name: "Ramada Investimentos e Industria,S.A.",
    mktCap: 173340000,
    mktCapPerf1Y: -6.63,
    sector: "Non-energy minerals",
  },
  {
    label: "SLBEN",
    name: "Sport Lisboa e Benfica-Futebol SA",
    mktCap: 157780000,
    mktCapPerf1Y: 16.34,
    sector: "Consumer services",
  },
  {
    label: "GLINT",
    name: "GLINTT GLOBAL, S.A.",
    mktCap: 109570000,
    mktCapPerf1Y: 50.9,
    sector: "Commercial services",
  },
  {
    label: "MLFMV",
    name: "Farminveste - SGPS SA Class B",
    mktCap: 105000000,
    mktCapPerf1Y: 138.63,
    sector: "Finance",
  },
  {
    label: "FCP",
    name: "Futebol Clube do Porto SAD",
    mktCap: 67500000,
    mktCapPerf1Y: 212.38,
    sector: "Consumer services",
  },
  {
    label: "PHR",
    name: "PHarol SGPS S.A.",
    mktCap: 59660000,
    mktCapPerf1Y: 33.09,
    sector: "Communications",
  },
  {
    label: "MLCIA",
    name: "CIAGEST - SIGI, S.A.",
    mktCap: 59270000,
    mktCapPerf1Y: 0.0,
    sector: "Finance",
  },
  {
    label: "ESON",
    name: "ESTORIL-SOL, SGPS, S.A.",
    mktCap: 36940000,
    mktCapPerf1Y: -18.6,
    sector: "Consumer services",
  },
  {
    label: "IPR",
    name: "Impresa SGPS SA",
    mktCap: 30810000,
    mktCapPerf1Y: 26.71,
    sector: "Consumer services",
  },
  {
    label: "CDU",
    name: "Conduril - Engenharia, S.A.",
    mktCap: 29800000,
    mktCapPerf1Y: -13.29,
    sector: "Industrial services",
  },
  {
    label: "SCB",
    name: "Sporting Clube de Braga-Futebol Sad",
    mktCap: 24000000,
    mktCapPerf1Y: 59.71,
    sector: "Consumer services",
  },
  {
    label: "FLEXD",
    name: "Flexdeal - SIMFE SA",
    mktCap: 17920000,
    mktCapPerf1Y: 2.52,
    sector: "Finance",
  },
  {
    label: "SNG",
    name: "Sonagi, S.G.P.S., S.A.",
    mktCap: 17000000,
    mktCapPerf1Y: 1.75,
    sector: "Finance",
  },
  {
    label: "MLRZE",
    name: "Raize-Instituicao De Pagamentos SA",
    mktCap: 6900000,
    mktCapPerf1Y: 100.0,
    sector: "Commercial services",
  },
];

export default data;
